### ISSUE TITLE
Íconos de redes sociales landing

### ISSUE THREAD

**Issue by alealonsoa** [ConceptHaus/landing_sistemaeco#4]
Los íconos de hasta abajo me aparecen encimados, hay que alinearlos para que no se vea así.

También el símbolo de twitter me esta redireccionando a linkedin, hay que corregir esto.
Instagram ya tenemos @sistemaeco_mx para redireccionar ahí el instagram.

![image](https://user-images.githubusercontent.com/31110731/29468148-a3d6937c-8408-11e7-8f7a-86447e0d6ef8.png)

**Comment by omarCastillo** [comment]
Falta link de Instagram

**Comment by alealonsoa** [comment]
https://www.instagram.com/sistemaeco_mx/

**Comment by omarCastillo** [comment]
Gracicas!
